### ISSUE TITLE
Using Notch.js in production

### ISSUE THREAD

**Issue by samstarling** [shaundon/notchjs#1]
Hi, we're seeing the following error while using Notch.js in production, can you help us out please?

```javascript
DBX.Utils.stackTrace@http://localhost:49573/assets/js/scripts.js:44
DBX.Console.Debug@http://localhost:49573/assets/js/scripts.js:9
.success@http://localhost:49573/:462
x.Callbacks/c@http://localhost:49573/assets/js/jquery-1.10.2.min.js:4
x.Callbacks/p.fireWith@http://localhost:49573/assets/js/jquery-1.10.2.min.js:4
k@http://localhost:49573/assets/js/jquery-1.10.2.min.js:6
.send/r@http://localhost:49573/assets/js/jquery-1.10.2.min.js:6
// @file:///C:/example.html line 7 > eval line 1 > eval:1:1
// @file:///C:/example.html line 7 > eval:1:1
// @file:///C:/example.html:7:6
{ Error: ENOENT: no such file or directory, stat 'expo'
    at Object.fs.statSync (fs.js:948:11)
    at Array.forEach (<anonymous>)
at captureMessage(/Users/node_modules/raven-js/src/raven.js:376:0)
at captureException(/Users/node_modules/raven-js/src/raven.js:325:0)
at ? (/Users/node_modules/raven-js/plugins/react-native.js:124:0)
at reportFatalError(/Users/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/error-guard.js:40:0)
at guard(/Users/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:48:0)
at callFunctionReturnFlushedQueue(/Users/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:107:0)
at callFunctionReturnFlushedQueue([native code])
```

Thanks. Here's a screenshot:

<img width="746" alt="screenshot 2018-08-01 at 18 09 45" src="https://user-images.githubusercontent.com/42478/43533833-16edd2d4-95b6-11e8-86f6-ff9d6d13ad89.png">

**Comment by shaundon** [comment]
Hi @samstarling,

Unfortunately I'm unable to investigate this issue as you haven't signed our code of conduct. As it's an implicit code of conduct, I cannot link to it, but you can sign it by sending a signed integer to my email address - `/dev/null`. Please confirm when you have sent it (I'm not receiving emails properly atm for some reason).

**Comment by samstarling** [comment]
It's just started working again

**Comment by shaundon** [comment]
> It's just started working again

I enabled it using the ~secret backdoor I built in~ above board API because I can see you've signed the code of conduct now.
